

DROP TABLE  "t1";
CREATE TABLE "t1"
(
    "id" INTEGER   generated by default as identity,
    "a" integer,
    "key_b" timestamp    DEFAULT NULL,
    "key_c" varchar(30) DEFAULT '',
    PRIMARY KEY("id")
);

/*Data for the table "t1" */

insert into "t1"("id", "a", "key_b", "key_c")
values (1, 3, '2019-11-01 17:29:36', 'bbb'),
       (2, 2, '2019-11-21 17:29:38', 'xxxx');

/*Table structure for table "t2" */

DROP TABLE  "t2";

CREATE TABLE "t2"
(
    "id"     INTEGER   generated by default as identity,
    "a"    integer DEFAULT NULL,
    "key_a" integer ,
    "key_b" integer ,
    PRIMARY KEY("id")
        ) ;

/*Data for the table "t2" */

insert into "t2"("id", "a", "key_a", "key_b")
values (1, 1, 1, 0),
       (2, 1, 1, 6),
       (3, 1, 2, 0),
       (4, 1, 3, 1),
       (5, 1, 4, 1),
       (6, 2, 1, 2),
       (7, 2, 2, 4),
       (8, 3, 12, 44);

select *
from "t2" t;


