
DROP DATABASE IF EXISTS demo_ds_0;
DROP DATABASE IF EXISTS demo_ds_1;
DROP DATABASE IF EXISTS demo_ds;
DROP DATABASE IF EXISTS demo_write_ds;
DROP DATABASE IF EXISTS demo_read_ds_0;
DROP DATABASE IF EXISTS demo_read_ds_1;
CREATE DATABASE demo_ds_0;
CREATE DATABASE demo_ds_1;
CREATE DATABASE demo_ds;
CREATE DATABASE demo_write_ds;
CREATE DATABASE demo_read_ds_0;
CREATE DATABASE demo_read_ds_1;
