/*
 Navicat Premium Data Transfer

 Source Server         : postgres
 Source Server Type    : PostgreSQL
 Source Server Version : 150000 (150000)
 Source Host           : 192.168.137.200:5432
 Source Catalog        : db_teacher_slave1
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150000 (150000)
 File Encoding         : 65001

 Date: 20/10/2022 10:06:15
*/


-- ----------------------------
-- Table structure for teacher
-- ----------------------------
DROP TABLE IF EXISTS "public"."teacher";
CREATE TABLE "public"."teacher" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(30) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of teacher
-- ----------------------------
INSERT INTO "public"."teacher" VALUES (1, 'liyi');
INSERT INTO "public"."teacher" VALUES (2, 'leiming');
INSERT INTO "public"."teacher" VALUES (3, 'sunquan');
INSERT INTO "public"."teacher" VALUES (4, 'futao');

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."teacher_id_seq"', max(id), true) from teacher;


-- ----------------------------
-- Primary Key structure for table teacher
-- ----------------------------
ALTER TABLE "public"."teacher" ADD CONSTRAINT "teacher_pkey" PRIMARY KEY ("id");
